In [2]:
import pandas as pd

# create a list of sentences
data = [
    "When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "iced tea is my favorite",
    "I didn't like the taste of that lemonade at all.",
    "My lemons went bad before I could use them, unfortunately.",
]

# expand the column width to see the full sentences
pd.set_option('display.max_colwidth', None)

# turn it into a dataframe
data_df = pd.DataFrame(data, columns=["sentence"])
data_df.head()

# make a copy of the dataframe
df = data_df.copy()
df.head()

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.

In [3]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [5]:
test  = df["sentence"][0]
test

'When life gives you lemons, make lemonade! 🙂'

In [6]:
analyzer = SentimentIntensityAnalyzer()
sentiment = analyzer.polarity_scores(test)
sentiment

{'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.4587}

In [7]:
def analyze_sentiment(sentence):
    analyzer = SentimentIntensityAnalyzer()
    sentiment = analyzer.polarity_scores(sentence)
    return sentiment

df["sentiment"] = df["sentence"].apply(analyze_sentiment)
df.head()

,sentence,sentiment
0,"When life gives you lemons, make lemonade! 🙂","{'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.4587}"
1,She bought 2 lemons for $1 at Maven Market.,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}"
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}"
3,"lemon, lemon, lemons, lemon, lemon, lemons","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}"
4,He's running to the market to get a lemon — there's a great sale today.,"{'neg': 0.0, 'neu': 0.773, 'pos': 0.227, 'compound': 0.6249}"

In [8]:
df.head(10)

,sentence,sentiment
0,"When life gives you lemons, make lemonade! 🙂","{'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.4587}"
1,She bought 2 lemons for $1 at Maven Market.,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}"
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}"
3,"lemon, lemon, lemons, lemon, lemon, lemons","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}"
4,He's running to the market to get a lemon — there's a great sale today.,"{'neg': 0.0, 'neu': 0.773, 'pos': 0.227, 'compound': 0.6249}"
5,iced tea is my favorite,"{'neg': 0.0, 'neu': 0.571, 'pos': 0.429, 'compound': 0.4588}"
6,I didn't like the taste of that lemonade at all.,"{'neg': 0.19, 'neu': 0.81, 'pos': 0.0, 'compound': -0.2755}"
7,"My lemons went bad before I could use them, unfortunately.","{'neg': 0.424, 'neu': 0.576, 'pos': 0.0, 'compound': -0.7096}"

In [9]:
testcommit = "test commit"
print(testcommit)

test commit